name: Prevent Self-Approved Merges

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review, review_requested]
  pull_request_review:
    types: [submitted]

jobs:
  check-author-vs-approver:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is self-approved
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          AUTHOR="${{ github.event.pull_request.user.login }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          REPO="${{ github.repository }}"

          echo "PR Author: $AUTHOR"
          echo "PR Number: $PR_NUMBER"

          # Get all reviews for the PR (GH CLI is already available on runner)
          APPROVERS=$(gh api repos/$REPO/pulls/$PR_NUMBER/reviews --jq '.[] | select(.state=="APPROVED") | .user.login' | sort | uniq)

          echo "Approvers: $APPROVERS"

          APPROVED_BY_OTHERS=false
          for user in $APPROVERS; do
            if [ "$user" != "$AUTHOR" ]; then
              APPROVED_BY_OTHERS=true
              break
            fi
          done

          if [ "$APPROVED_BY_OTHERS" = false ]; then
            echo "This PR was only approved by its author, which is not allowed."
            exit 1
          else
            echo "This PR was approved by someone other than the author."
          fi
